-- This script populates the vector_rules table with data, omitting regex patterns.
TRUNCATE TABLE vector_rules RESTART IDENTITY;

INSERT INTO vector_rules (id, title, description, category, severity, language, suggestion)
VALUES
    -- Bad Practices
    (1, 'Avoid Using SELECT *', 'Fetching all columns with SELECT * is inefficient and can cause issues if the table schema changes. It leads to unnecessary data transfer and can break dependent code.', 'Performance', 'Major', 'SQL', 'Specify only the required column names instead of using SELECT *.'),
    (2, 'Avoid Leading Wildcards in LIKE', 'A LIKE clause with a leading wildcard (e.g., ''%text'') prevents the database from using an index on that column, forcing a full table scan.', 'Performance', 'Major', 'SQL', 'Whenever possible, anchor the search term in a LIKE clause. For example, use ''text%'' instead of ''%text''.'),
    (3, 'Avoid DELETE without a WHERE Clause', 'A DELETE statement without a WHERE clause removes all rows from a table. This is often an unintentional, destructive action.', 'Data Integrity', 'Major', 'SQL', 'If you intend to clear the entire table, use the TRUNCATE TABLE statement for better performance and clarity. Otherwise, always include a WHERE clause.'),
    (4, 'Use Explicit JOINs Instead of Implicit', 'Implicit joins using a comma in the FROM clause are an old syntax that can lead to accidental cross joins and are harder to read.', 'Clarity', 'Minor', 'SQL', 'Always use explicit JOIN syntax (e.g., INNER JOIN, LEFT JOIN) to clearly define the relationship between tables.'),
    (5, 'Avoid Using NOLOCK Hint', 'The NOLOCK hint (or READUNCOMMITTED) allows queries to read uncommitted data, which can lead to dirty reads and data inconsistency.', 'Data Integrity', 'Critical', 'SQL', 'Remove the NOLOCK hint. For better concurrency, consider using snapshot isolation levels if available.'),
    (6, 'Avoid Functions on Indexed Columns in WHERE', 'Applying a function to a column in a WHERE clause (e.g., WHERE YEAR(date_col) = 2023) prevents the database from using an index on that column.', 'Performance', 'Major', 'SQL', 'Restructure the query to apply the function to the value, not the column. For example, use WHERE date_col >= ''2023-01-01'' AND date_col < ''2024-01-01''.'),
    (7, 'Avoid Using COUNT(*)', 'Using COUNT(*) to count all rows can be inefficient as it may require the database to check all columns. It is generally better for performance to count a single, constant value.', 'Performance', 'Minor', 'SQL', 'Use COUNT(1) or COUNT(primary_key_column) instead of COUNT(*) for better performance when counting all rows.'),
    (8, 'Do Not Use HAVING as a Substitute for WHERE', 'The HAVING clause is designed to filter the results of an aggregate function (like SUM or COUNT), not to filter rows. Using it for row-level filtering is inefficient.', 'Performance', 'Minor', 'SQL', 'Use the WHERE clause for all row-level filtering before the GROUP BY clause. Reserve HAVING for filtering on aggregate values.'),
    (9, 'Use Table Aliases in Multi-Table Queries', 'When a query involves joins or multiple tables, failing to use table aliases can make the query difficult to read and maintain.', 'Clarity', 'Minor', 'SQL', 'Assign short, intuitive aliases to all tables in a query (e.g., FROM products p JOIN categories c) and use them to qualify all column names.');
